### ISSUE TITLE
GlobStart recursive ** matching is broken

### ISSUE THREAD

**Issue by emidoots** [mb0/glob#1]
Beware it is broken ... implemented as just a print statement! :see_no_evil: :speak_no_evil: :hear_no_evil: 

https://github.com/mb0/glob/blob/master/glob.go#L290

**Comment by mb0** [comment]
i falsely remember to have finished this. i hope this obvious fix is all that was missing from that feature.
if there is more missing i will take some time to get into context and look at it properly.

thanks for reporting and sorry for the inconvenience.

**Comment by emidoots** [comment]
Nice, thanks! If I run into more issues I'll be sure to report :)
