### ISSUE TITLE
Caveats with GlobStar matching

### ISSUE THREAD

**Issue by emidoots** [mb0/glob#2]
This program prints `false <nil>`:

```
package main

import (
    "fmt"

    "github.com/mb0/glob"
)

func main() {
    m, err := glob.Match("**/*.go", "go-sourcegraph/sourcegraph/foobar.go")
    fmt.Println(m, err)
}
```

Replacing the pattern with `**/foobar.go` causes it to print `true <nil>` instead. i.e. start matching does not work in combination with the recursive GlobStar `**` matching

**Comment by mb0** [comment]
i took more time for this issue. if that does not fix things i'll rewrite it as a glob to regex transformer.

sorry for the inconvenience.
